# Device name
dev_id   usb-Sony_Computer_Entertainment_Wireless_Controller-if03-event-joystick

disable_passthrough

# variables
acceleration  0.5
max_speed     20
break_factor  0.2
wheel         60

# keys
left          ABS_RX     128..0
right         ABS_RX     128..255
up            ABS_RY     128..0
down          ABS_RY     128..255
right_click   BTN_TL2
left_click    BTN_TR2
scroll_up     ABS_Y      128..0
scroll_down   ABS_Y      128..255
scroll_click  BTN_THUMBL
backward      BTN_TL
forward       BTN_TR
mouse_break   BTN_WEST
