# Device name
dev_id   usb-SteelSeries_SteelSeries_Apex_3-event-kbd

# variables
acceleration  0.5
max_speed     20
break_factor  0.2

enable_passthrough

# keys
 up            KEY_KP8
 down          KEY_KP5
 left          KEY_KP4
 right         KEY_KP6
right_click   KEY_KPPLUS
left_click    KEY_KP0
scroll_down   KEY_KP3
scroll_up     KEY_KP1
scroll_click  KEY_KP2
backward     KEY_KP7
forward      KEY_KP9
mouse_break   ! KEY_LEFTSHIFT
