# keyboard name
phys_name   = usb-0000:2f:00.3-1.3/input0

# variables
acceleration = 0.5
max_speed    = 20
break_factor = 0.2

# keys
up           = KEY_KP8
down         = KEY_KP5
left         = KEY_KP4
right        = KEY_KP6
right_click  = KEY_KP9
left_click   = KEY_KP7
scroll_down  = KEY_KP3
scroll_up    = KEY_KP1
scroll_click = KEY_KP2
mouse_break  = ! KEY_LEFTSHIFT
